// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-qJZUq7t1HJIjgqwBTTyZtvBA3X3Xdug',
    appId: '1:308159769865:web:cba8d407a96ecca35937d8',
    messagingSenderId: '308159769865',
    projectId: 'client-app-84b3d',
    authDomain: 'client-app-84b3d.firebaseapp.com',
    storageBucket: 'client-app-84b3d.firebasestorage.app',
    measurementId: 'G-81Y1XQVKMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOkG3qD0UExk5xf7W42oJFJ-SiIzEizuc',
    appId: '1:308159769865:android:54cad2ccacf015b25937d8',
    messagingSenderId: '308159769865',
    projectId: 'client-app-84b3d',
    storageBucket: 'client-app-84b3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBemVcWoOrSU6eRbx_Ne-rCNjx4Vn5LMVw',
    appId: '1:308159769865:ios:b418d0f713d090585937d8',
    messagingSenderId: '308159769865',
    projectId: 'client-app-84b3d',
    storageBucket: 'client-app-84b3d.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBemVcWoOrSU6eRbx_Ne-rCNjx4Vn5LMVw',
    appId: '1:308159769865:ios:b418d0f713d090585937d8',
    messagingSenderId: '308159769865',
    projectId: 'client-app-84b3d',
    storageBucket: 'client-app-84b3d.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-qJZUq7t1HJIjgqwBTTyZtvBA3X3Xdug',
    appId: '1:308159769865:web:33e28852e43cf6dd5937d8',
    messagingSenderId: '308159769865',
    projectId: 'client-app-84b3d',
    authDomain: 'client-app-84b3d.firebaseapp.com',
    storageBucket: 'client-app-84b3d.firebasestorage.app',
    measurementId: 'G-XSFH60W4SD',
  );
}
